### ISSUE TITLE
There is no humanml_opt.txt

### ISSUE THREAD

**Issue by JinEui-Kim** [zhenzhiwang/intercontrol#1]
Hi! i love your great job.
but i have no idea where is humanml_opt.txt during sampling in Human Interaction Generation part.
Here is my error messages.

```
(intercontrol) td@td:~/Project/intercontrol$ python3 -m eval.eval_interaction --model_path save/my_humanml_trans_enc_512/model000120000.pt --replication_times 10 --bfgs_times_first 5 --bfgs_times_last 10 --bfgs_interval 1 --use_posterior  --control_joint all --interaction_json './assets/all_plans.json' --multi_person
Warning: was not able to load [use_tta], using default value [False] instead.
Warning: was not able to load [concat_trans_emb], using default value [False] instead.
Warning: was not able to load [trans_emb], using default value [False] instead.
Using inpainting mask: global_joint
Will save to log file [save/my_humanml_trans_enc_512/interactive_niter_120000_all_mask1_bfgs_first5_last10_skip1_posterior_wo_mm.log]
Eval mode [wo_mm]
Logging to /tmp/openai-2023-11-29-21-43-32-799527
creating humanml loader...
Reading ././dataset/humanml_opt.txt
Traceback (most recent call last):
  File "/home/td/anaconda3/envs/intercontrol/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/td/anaconda3/envs/intercontrol/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/td/Project/intercontrol/eval/eval_interaction.py", line 159, in <module>
    gen_loader = get_dataset_loader(name=args.dataset, batch_size=args.batch_size, num_frames=None, split=split, load_mode='eval', size=1)  # humanml only for loading diffusion model config
  File "/home/td/Project/intercontrol/data_loaders/get_data.py", line 78, in get_dataset_loader
    dataset = get_dataset(name, num_frames, split, load_mode, batch_size, opt, short_db, cropping_sampler, size)
  File "/home/td/Project/intercontrol/data_loaders/get_data.py", line 57, in get_dataset
    dataset = DATA(split=split, num_frames=num_frames, load_mode=load_mode, size=size)
  File "/home/td/Project/intercontrol/data_loaders/humanml/data/dataset.py", line 1074, in __init__
    opt = get_opt(dataset_opt_path, device)
  File "/home/td/Project/intercontrol/data_loaders/humanml/utils/get_opt.py", line 37, in get_opt
    with open(opt_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '././dataset/humanml_opt.txt'
```

Also the model_path in README is wrong, so i change the path in my test case.
Thank you

**Comment by zhenzhiwang** [comment]
Hi Kim,

Thanks for your interest of our work! Sorry for the incomplete information of readme. For humanml_opt.txt, I will upload it later. For other dependencies, I will check the MDM and PriorMDM repo to see what are necessary for my repo. Finally, the MDM checkpoint "my_humanml_trans_enc_512" is a pretrained text-conditioned motion generation model without controlnet, which is the init of my model during the training process. I will also upload my checkpoint for directly sampling interactions and the evalution later. Hopefully I will finish all things this weekend. 

By the way, sampling interactions should use --interaction_json './assets/sample.json', where you could copy part of contact pairs from all_plans.json to sample.json, or write your own contact pairs. 'all_plans.json' is for interaction evaluation.

Please ask further questions if there is still something wrong after I update this code.

**Comment by JinEui-Kim** [comment]
Thank you for answer!

I'll retry after you update the code.
Thanks agian!

**Comment by zhenzhiwang** [comment]
Hi Kim,

I have uploaded the humanml_opt.txt and checkpoints for direct motion generation and evaluation. Please have a look and check whether this version is good to run. I configured the environment a long time ago, so things running well in my server may lead to unexpected errors in servers of new users. Thank you for helping me with such issues.

**Comment by JinEui-Kim** [comment]
I tried to do but the pre-trained model link is not public, so i can't download that.
Here is the list that i can't download due to permission.

- all joints control, finetuned for sparse signals in temporal [mask0.25_bfgs5_posterior_all]
- all joints control, checkpoint for HumanML3D dataset evalution [mask1_bfgs5_posterior_all]
- all joints control [mask1_x0_all]
- pelvis control [mask1_x0_pelvis]

Thank you!

**Comment by zhenzhiwang** [comment]
Hi Kim,
Sorry that I didn't change the visability of google drive link. Could you try this again? I have changed the link to be public.

**Comment by JinEui-Kim** [comment]
https://github.com/zhenzhiwang/intercontrol/assets/114208539/1757be90-7114-41da-9478-1d448b3e84d1

Great Everything is fine!
