### ISSUE TITLE
Sampling more than 3 people interaction

### ISSUE THREAD

**Issue by wngTn** [zhenzhiwang/intercontrol#4]
Hey,  very interesting work!

I'm curious whether I recreated the "3 people interaction sampling" correctly.
I haven't quite looked through all the code, but simply running:
`python -m sample.more_people_global_joint_control --model_path save/mask0.25_bfgs5_posterior_all/model000140000.pt --multi_person --bfgs_times_first 5 --bfgs_times_last 10 --use_posterior`
leads to interactions of only two people instead of three or more, as depicted in the output videos.

Is this expected behavior? Or are there additional things that need to be considered to actually create interactions of three or more people?

https://github.com/zhenzhiwang/intercontrol/assets/54139364/68448f02-bd1d-42b7-9412-e46d131fd9d8

https://github.com/zhenzhiwang/intercontrol/assets/54139364/3948af0b-6c66-4761-8bb5-d9f41bb467bd

**Comment by zhenzhiwang** [comment]
Hi [wngTn](https://github.com/wngTn), thanks for your interest of our work! The matplotlib visualization only contains at most 2 people. Please use all the outputed .npy file that each file contains one motion to the blender to visualize group motions with more than two people. 
The final visualization will look like this.
![Screenshot 2024-07-10 at 10 52 08](https://github.com/zhenzhiwang/intercontrol/assets/26179848/ff6a9626-e31f-4a98-98cd-0aefc00e1213)
